const URL='https://jdumqdatenehmcxwiztc.supabase.co';
const KEY='sb_publishable_TdG-fJSXKyKEKnqVPFomuA_aDYAI_t0';
const OWNER='f4865679-4a91-412a-b58f-0650d3d70cae';
const EMAIL='odeeil1085@gmail.com';
const VISION=URL+'/functions/v1/my-brain-vision';
let session=null,items=[],topics=[],bulkFiles=[],mailFiles=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtBytes=n=>{n=Number(n)||0;if(!n)return'0 MB';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i<2?0:1)} ${u[i]}`};
const token=()=>session?.access_token||sessionStorage.getItem('mb_token')||'';
const authHeaders=()=>({apikey:KEY,Authorization:'Bearer '+token()});
function setStatus(id,text,ok=true){const e=$(id);if(!e)return;e.textContent=text;e.className='status '+(ok?'ok':'err')}
async function parse(r){const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(j.message||j.error_description||j.error||text||`HTTP ${r.status}`);return j}
async function authFetch(url,opt={},retry=true){let r=await fetch(url,{...opt,headers:{...(opt.headers||{}),...authHeaders()}});if(r.status===401&&retry&&sessionStorage.getItem('mb_refresh')){await refreshAuth();r=await fetch(url,{...opt,headers:{...(opt.headers||{}),...authHeaders()}})}return r}
async function refreshAuth(){const rt=sessionStorage.getItem('mb_refresh');const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt})});const j=await parse(r);saveSession(j);return j}
function saveSession(j){session=j;sessionStorage.setItem('mb_token',j.access_token||'');if(j.refresh_token)sessionStorage.setItem('mb_refresh',j.refresh_token)}
async function rest(path,opt={}){return parse(await authFetch(URL+'/rest/v1/'+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}))}
async function login(){setStatus('#loginMsg','מתחבר…',true);try{const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:EMAIL,password:$('#password').value})});const j=await parse(r);if(j.user?.id!==OWNER)throw new Error('החשבון אינו מורשה');saveSession(j);await enter()}catch(e){setStatus('#loginMsg','שגיאה: '+e.message,false)}}
async function recover(){if(!token())return false;try{let r=await fetch(URL+'/auth/v1/user',{headers:authHeaders()});if(r.status===401){await refreshAuth();r=await fetch(URL+'/auth/v1/user',{headers:authHeaders()})}const u=await parse(r);if(u.id!==OWNER)return false;session={access_token:token(),user:u};return true}catch{return false}}
async function enter(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');await reloadAll();showView('home')}
function logout(){sessionStorage.clear();location.reload()}
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='bulk')fillTopicSelects()}
async function reloadAll(){await Promise.all([loadTopics(),loadItems()]);render()}
async function loadTopics(){topics=await rest('topics?select=*&order=created_at.asc')}
async function loadItems(){items=await rest('knowledge_items?select=*&order=created_at.desc&limit=500')}
function topicPath(id){const parts=[];let t=topics.find(x=>x.id===id),guard=0;while(t&&guard++<20){parts.unshift(t.name);t=topics.find(x=>x.id===t.parent_id)}return parts.join(' / ')}
function fillTopicSelects(){const opts='<option value="">Inbox / ללא נושא</option>'+topics.map(t=>`<option value="${t.id}">${esc(topicPath(t.id))}</option>`).join('');['#bulkTopic','#mailTopic'].forEach(s=>{if($(s))$(s).innerHTML=opts})}
function render(){const docs=items.filter(i=>i.item_type==='document'),imgs=items.filter(i=>i.item_type==='image');$('#stItems').textContent=items.length;$('#stTopics').textContent=topics.length;$('#stDocs').textContent=docs.length;$('#stImages').textContent=imgs.length;$('#recent').innerHTML=items.slice(0,10).map(itemHtml).join('')||empty('אין עדיין פריטים');$('#allItems').innerHTML=items.map(itemHtml).join('')||empty('אין עדיין פריטים');$('#docs').innerHTML=docs.map(itemHtml).join('')||empty('אין מסמכים');$('#images').innerHTML=imgs.map(imageHtml).join('')||empty('אין תמונות');$('#topics').innerHTML=topics.map(topicHtml).join('')||empty('אין Topics');fillTopicSelects();hydrateImages()}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function itemHtml(i){const icon=i.item_type==='image'?'▧':i.item_type==='document'?'▤':i.item_type==='email'?'✉':'✎';return `<div class="item" onclick="openItem('${i.id}')"><div class="itemtop"><div class="icon">${icon}</div><div class="grow"><b>${esc(i.title)}</b><div class="small muted">${esc(i.item_type)}${i.topic_id?' · '+esc(topicPath(i.topic_id)):''} · ${new Date(i.created_at).toLocaleDateString('he-IL')}</div>${i.extracted_text?`<div class="small muted">${esc(i.extracted_text.slice(0,150))}</div>`:''}</div></div></div>`}
function imageHtml(i){return `<div class="imagecard" onclick="openItem('${i.id}')"><img data-path="${esc(i.storage_path||'')}" alt=""><div><b>${esc(i.title)}</b><div class="small muted">${new Date(i.created_at).toLocaleDateString('he-IL')}</div></div></div>`}
function topicHtml(t){return `<div class="topic" onclick="filterTopic('${t.id}')"><b>⌘ ${esc(t.name)}</b><div class="small muted">${esc(t.description||'')||'ללא תיאור'}</div><div class="small muted">${items.filter(i=>i.topic_id===t.id).length} פריטים</div></div>`}
window.filterTopic=id=>{showView('all');$('#allTitle').textContent='Topic: '+topicPath(id);$('#allItems').innerHTML=items.filter(i=>i.topic_id===id).map(itemHtml).join('')||empty('אין פריטים ב־Topic הזה')};
async function signedUrl(path,seconds=600){const j=await parse(await authFetch(URL+'/storage/v1/object/sign/my-brain-files/'+encodeURIComponent(path).replace(/%2F/g,'/'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:seconds})}));return URL+'/storage/v1'+j.signedURL}
async function hydrateImages(){for(const img of $$('img[data-path]').slice(0,60)){if(img.dataset.loaded||!img.dataset.path)continue;img.dataset.loaded='1';try{img.src=await signedUrl(img.dataset.path,900)}catch{}}}
window.openItem=async id=>{const i=items.find(x=>x.id===id);if(!i)return;$('#drawerTitle').textContent=i.title;$('#drawerMeta').textContent=(i.item_type||'')+(i.topic_id?' · '+topicPath(i.topic_id):'')+' · '+new Date(i.created_at).toLocaleString('he-IL');const p=$('#drawerPreview');p.innerHTML=i.extracted_text?`<div class="panel"><b>טקסט שחולץ</b><p>${esc(i.extracted_text)}</p></div>`:'';if(i.storage_path){try{const u=await signedUrl(i.storage_path,600);if(i.item_type==='image'||i.mime_type?.startsWith('image/'))p.innerHTML=`<img src="${u}">`+p.innerHTML;else if(i.mime_type?.includes('pdf')||i.original_filename?.toLowerCase().endsWith('.pdf'))p.innerHTML=`<iframe src="${u}"></iframe>`+p.innerHTML;$('#openSource').onclick=()=>window.open(u,'_blank');$('#openSource').classList.remove('hidden')}catch{$('#openSource').classList.add('hidden')}}else $('#openSource').classList.add('hidden');$('#backdrop').classList.remove('hidden');$('#drawer').classList.remove('hidden')};
function closeDrawer(){$('#backdrop').classList.add('hidden');$('#drawer').classList.add('hidden')}
async function uploadStorage(file,path,progress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',URL+'/storage/v1/object/my-brain-files/'+encodeURIComponent(path).replace(/%2F/g,'/'));x.setRequestHeader('apikey',KEY);x.setRequestHeader('Authorization','Bearer '+token());x.setRequestHeader('Content-Type',file.type||'application/octet-stream');x.setRequestHeader('x-upsert','false');x.upload.onprogress=e=>{if(e.lengthComputable)progress(Math.round(e.loaded/e.total*100))};x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error(x.responseText||'Upload '+x.status));x.onerror=()=>reject(new Error('שגיאת רשת'));x.send(file)})}
async function analyzeImage(item){if(!item.storage_path)return;try{await rest('knowledge_items?id=eq.'+item.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({index_status:'processing',index_error:null})});const r=await authFetch(VISION,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storage_path:item.storage_path,mime:item.mime_type||'image/jpeg'})});const j=await parse(r);await rest('knowledge_items?id=eq.'+item.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({extracted_text:String(j.text||''),index_status:'ready',index_error:null,metadata:{...(item.metadata||{}),vision_provider:j.provider||null,vision_at:new Date().toISOString()}})})}catch(e){await rest('knowledge_items?id=eq.'+item.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({index_status:'failed',index_error:String(e.message||e).slice(0,300)})}).catch(()=>{})}}
function renderFileQueue(){const q=$('#fileQueue');q.innerHTML=bulkFiles.map((f,i)=>`<div class="qrow"><div class="row between"><b class="small">${esc(f.name)}</b><span class="small muted">${fmtBytes(f.size)}</span></div><div class="progress"><div id="bar${i}"></div></div><div id="fst${i}" class="small muted">ממתין</div></div>`).join('')}
async function runFileUpload(){if(!bulkFiles.length)return setStatus('#bulkStatus','בחר קבצים קודם',false);const btn=$('#bulkUpload');btn.disabled=true;let ok=0,fail=0;try{const topic=$('#bulkTopic').value||null;for(let i=0;i<bulkFiles.length;i++){const f=bulkFiles[i],type=(f.type||'').startsWith('image/')?'image':'document',path=OWNER+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');try{await uploadStorage(f,path,p=>{$('#bar'+i).style.width=p+'%';$('#fst'+i).textContent='מעלה… '+p+'%'});const row={user_id:OWNER,topic_id:topic,item_type:type,title:f.name,storage_path:path,mime_type:f.type||null,original_filename:f.name,metadata:{size:f.size,bulk_import:true},index_status:type==='image'?'processing':'ready',index_error:null};const created=(await rest('knowledge_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];$('#fst'+i).textContent='נשמר';ok++;if(type==='image')await analyzeImage(created)}catch(e){$('#fst'+i).textContent='נכשל: '+e.message;fail++}}await reloadAll();setStatus('#bulkStatus',`הועלו ${ok} קבצים${fail?' · '+fail+' נכשלו':''}`,fail===0)}finally{btn.disabled=false}}
function headerValue(h,name){const m=h.replace(/\r?\n[ \t]+/g,' ').match(new RegExp('^'+name+':\\s*(.*)$','im'));return m?m[1].trim():''}
function stripHtml(s){const d=document.createElement('div');d.innerHTML=s;return(d.textContent||d.innerText||'').trim()}
function parseMail(raw,source){const idx=raw.search(/\r?\n\r?\n/),h=idx>=0?raw.slice(0,idx):raw,b=idx>=0?raw.slice(idx).replace(/^\r?\n\r?\n/,''):'';const ct=headerValue(h,'Content-Type').toLowerCase();return{user_id:OWNER,item_type:'email',title:headerValue(h,'Subject')||'Email ללא נושא',body_text:(ct.includes('text/html')?stripHtml(b):b).slice(0,500000),metadata:{from:headerValue(h,'From'),to:headerValue(h,'To'),date:headerValue(h,'Date'),message_id:headerValue(h,'Message-ID'),source_file:source,bulk_import:true},index_status:'ready',index_error:null}}
function splitMbox(raw){return raw.replace(/\r\n/g,'\n').split(/\n(?=From [^\n]+\n)/).map(x=>x.replace(/^From [^\n]*\n/,'')).filter(x=>x.trim())}
function renderMailQueue(){$('#mailQueue').innerHTML=mailFiles.map(f=>`<div class="qrow"><b class="small">${esc(f.name)}</b> <span class="small muted">${fmtBytes(f.size)}</span></div>`).join('')}
async function runMailImport(){if(!mailFiles.length)return setStatus('#mailStatus','בחר EML או MBOX קודם',false);const btn=$('#mailImport');btn.disabled=true;try{const topic=$('#mailTopic').value||null,rows=[];for(const f of mailFiles){const raw=await f.text();if(/\.mbox$/i.test(f.name))splitMbox(raw).forEach((m,i)=>{const r=parseMail(m,f.name+'#'+(i+1));r.topic_id=topic;rows.push(r)});else{const r=parseMail(raw,f.name);r.topic_id=topic;rows.push(r)}}let done=0;for(let i=0;i<rows.length;i+=40){const batch=rows.slice(i,i+40);await rest('knowledge_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(batch)});done+=batch.length;setStatus('#mailStatus',`מייבא ${done} מתוך ${rows.length}…`,true)}await reloadAll();setStatus('#mailStatus',`הייבוא הסתיים: ${done} מיילים נשמרו`,true)}catch(e){setStatus('#mailStatus','שגיאה: '+e.message,false)}finally{btn.disabled=false}}
async function createTopic(){const name=prompt('שם ה־Topic');if(!name)return;const description=prompt('תיאור (לא חובה)')||null;try{await rest('topics',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:OWNER,name,description,parent_id:null})});await reloadAll()}catch(e){alert(e.message)}}
async function addNote(){const title=prompt('כותרת');if(!title)return;const body=prompt('תוכן')||'';try{await rest('knowledge_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:OWNER,item_type:'note',title,body_text:body,index_status:'ready',index_error:null})});await reloadAll()}catch(e){alert(e.message)}}
async function searchNow(){const q=$('#search').value.trim().toLowerCase();showView('all');$('#allTitle').textContent=q?'תוצאות חיפוש':'All Knowledge';const res=q?items.filter(i=>[i.title,i.body_text,i.extracted_text,i.original_filename,JSON.stringify(i.metadata||{})].join(' ').toLowerCase().includes(q)):items;$('#allItems').innerHTML=res.map(itemHtml).join('')||empty('לא נמצאו תוצאות')}
function bindDrop(zone,input,setter,renderer,filter){zone.onclick=()=>input.click();zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag')};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');setter([...e.dataTransfer.files].filter(filter||(()=>true)));renderer()};input.onchange=()=>{setter([...input.files].filter(filter||(()=>true)));renderer()}}
function init(){
  $('#loginBtn').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#logout').onclick=logout;$('#addNote').onclick=addNote;$('#newTopic').onclick=createTopic;$('#bulkUpload').onclick=runFileUpload;$('#mailImport').onclick=runMailImport;$('#searchBtn').onclick=searchNow;$('#search').onkeydown=e=>{if(e.key==='Enter')searchNow()};$$('[data-nav]').forEach(b=>b.onclick=()=>showView(b.dataset.nav));$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;
  bindDrop($('#fileDrop'),$('#bulkFiles'),x=>bulkFiles=x,renderFileQueue);bindDrop($('#mailDrop'),$('#mailFiles'),x=>mailFiles=x,renderMailQueue,f=>/\.(eml|mbox)$/i.test(f.name));
  recover().then(ok=>ok&&enter());
}
document.addEventListener('DOMContentLoaded',init);
